/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moyskleytech.obsidianstacker;

import java.util.Arrays;
import java.util.List;

import org.bukkit.block.Block;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import com.moyskleytech.obsidian.material.ObsidianMaterial;
import com.moyskleytech.obsidianstacker.api.Stack;
import com.moyskleytech.obsidianstacker.api.StackerAPI;
import com.moyskleytech.obsidianstacker.api_impl.StackerAPIImpl;
import com.moyskleytech.obsidianstacker.configuration.Configuration;
import com.moyskleytech.obsidianstacker.listeners.PlaceBreakListener;
import com.moyskleytech.obsidianstacker.utils.StackUtils;

public class Main extends JavaPlugin {
    private StackerAPIImpl api;
    private PlaceBreakListener placeBreak;
    private Configuration configuration;
    
    public StackerAPIImpl getApi() {
        return api;
    }

    @Override
    public void onEnable() {
        super.onEnable();
        api = new StackerAPIImpl(this);

        placeBreak = new PlaceBreakListener(this);
        configuration = new Configuration();

    }

    @Override
    public @Nullable List<String> onTabComplete(@NotNull CommandSender sender, @NotNull Command command,
            @NotNull String alias, @NotNull String[] args) {
        return List.of("reload", "whatis");
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label,
            @NotNull String[] args) {
        if (args.length > 0 && "reload".equals(args[0])) {
            if (sender.hasPermission("obsidianstacker.reload")) {
                Configuration.getInstance().reload();
            }
        }
        if (args.length > 0 && "whatis".equals(args[0])) {
            Player player = (Player) sender;
            ObsidianMaterial match = ObsidianMaterial.match(player.getTargetBlockExact(12));
            if (match != null)
                sender.sendMessage(match.normalizedName());
            else
                sender.sendMessage("?");
        }
        return true;
    }
}
