/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    `maven-publish`
}

group = "com.moyskleytech"
version = "1.0.0"
description = "ObsidianStackerAPI"

repositories {
    maven("https://moyskleytech.com/debian/m2")
    maven("https://papermc.io/repo/repository/maven-public/")
    mavenCentral()
    mavenLocal()
}

dependencies {
    compileOnly("com.moyskleytech:ObsidianMaterialAPI:1.0.8")
    compileOnly("dev.folia:folia-api:1.20.2-R0.1-SNAPSHOT")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        setGroupId("com.moyskleytech")
        setArtifactId("ObsidianStackerAPI")
        setVersion(version)
        artifact(tasks["jar"])
    }
}
task<Exec>("publishToM2") {
    dependsOn("publishToMavenLocal")
    commandLine("bash", "-c", "scp -r ~/.m2/repository/com/moyskleytech/ObsidianStackerAPI/"+version+" moyskleytech.cloud:/opt/deb/m2/com/moyskleytech/ObsidianStackerAPI")
}

tasks {

    test {
        useJUnitPlatform()
        java.sourceCompatibility = JavaVersion.VERSION_1_8
    }

    compileJava {
        options.encoding = "UTF-8"
    }
     // Process Placeholders for the plugin.yml
    processResources {
        from("src/resources")
        filesMatching("**/plugin.yml") {
            expand(rootProject.project.properties)
        }

        // Always re-run this task
        outputs.upToDateWhen { false }
    }
}